# --- PENGATURAN NAVIGASI HEADER (Menu Laci) ---
header_pages:
  - profil-sekolah.md
  - guru-staf.md
  - kegiatan.md
  - prestasi.md
  - blog.md
  - galeri.md

# PENTING: MENYETEL JUDUL SITUS MENJADI KOSONG
# Ini memaksa Jekyll merender string kosong alih-alih 'Suhartanto74'
title: " "

# TEMA: Gunakan tema minimalis dan nonaktifkan header bawaan
remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-remote-theme
